# Generated by Django 5.2.1 on 2025-06-06 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Murders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='murders/')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Investigators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='investigations/')),
                ('murders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='main.murders')),
            ],
        ),
        migrations.CreateModel(
            name='Suspects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='suspects/')),
                ('murders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='main.murders')),
            ],
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='interviews/')),
                ('investigators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='main.investigators')),
                ('murders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='main.murders')),
                ('suspects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='main.suspects')),
            ],
        ),
    ]
