# Generated by Django 5.2.1 on 2025-06-06 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='murders',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='investigators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='investigations/')),
                ('murders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='main.murders')),
            ],
        ),
        migrations.CreateModel(
            name='suspects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='suspects/')),
                ('murders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='main.murders')),
            ],
        ),
        migrations.CreateModel(
            name='interviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='interviews/')),
                ('investigators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='main.investigators')),
                ('suspects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='main.suspects')),
            ],
        ),
    ]
