# Generated by Django 5.2.1 on 2025-06-06 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_murders_date_investigators_suspects_interviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='murders',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='main.murders'),
            preserve_default=False,
        ),
    ]
