# Generated by Django 5.2.1 on 2025-06-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chatroom_chatmessage_delete_contactquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='murder_case',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
